# Generated by Django 4.0 on 2022-12-13 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bloodPressure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodpressurerecord',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
