# Generated by Django 4.0 on 2022-12-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodPressure', '0002_bloodpressurerecord_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodpressurerecord',
            old_name='user_id',
            new_name='user',
        ),
    ]
